### ISSUE TITLE
User Login & Signup

### ISSUE THREAD

**Issue by mpeng8** [mpeng8/PyTrade#18]
## Story/Task Details
- [ ] Enable user login & signup page switch
- [ ] Connect user login& sign up with database

## Acceptance Scenarios

Given: A registered user is in the system
When: the user enters a correct id and password
Then: the user session is created and the user is taken to their dashboard page

Given: An unregistered user is in the system
When: the user enters any password or id
Then: they are notified of login failure and an entry is made in the server security log
Given: A registered user is in the system

When: the user enters a correct id, but an incorrect password
Then: they are notified of login failure and an entry is made in the server security log

## Done Done Criteria
The scenarios are running correctly without error and the database should be consistent with the webpage.

**Comment by mxie33** [comment]
Some concerns when creating the database:
1. website construction: a file called base.html can be created to include the structure code such as the whole dashboard menu design.
2. database design: For admin and user, should we create a separate model called admin or use a boolean called "customer" to separate admins and customers?
3. Need to think about the future architecture design: file naming, function naming, and problems such as "which function should be in which file?" etc...
