### ISSUE TITLE
Database creation based on EER diagram

### ISSUE THREAD

**Issue by mxie33** [mpeng8/PyTrade#6]
## Story/Task Details
- [ ] Database creation using sqlite
- [ ] Database connection with flask frame

## Acceptance Scenarios
- Given: A user with PyTrade
- When: the user clicks the webpage
- Then: the application should make successful sql call to the database.

## Done Done Criteria
Database should be created successfully, with tables and relations.

**Comment by mpeng8** [comment]
Due Jan 27th
