### ISSUE TITLE
Stock Database

### ISSUE THREAD

**Issue by mpeng8** [mpeng8/PyTrade#9]
**Story/Task Details**

-Integrate Stock Database with the prototype. 
 
**Acceptance Scenarios**

Given: A registered user on their dashboard page
When: the stock price is clicked
Then: The system should send api calls to the stock database.

**Done Done Criteria**
The database should be integrated with current code without any error or new bug.

**Comment by mongazer** [comment]
price data - quandl - done

data for fundamental analysis - in progress

**Comment by mpeng8** [comment]
price data - quandl - done

data for fundamental analysis - in progress
